### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by githubteacher**
This pull request updates the README.md. Resolve the merge conflicts and make sure the final version of the README.md is accurate and descriptive.

If you need any help resolving this conflict, check out this video: https://vimeo.com/225086807/17d3c84475

### CODE REVIEW

**Comment by peter-moraza** [comment]
Reviewing README.md

**Comment by peter-moraza** [comment]
@crichID Hi Cynthia, I don't have the "Resolve Conflicts" icon in my copy of the pull request. What am I overlooking?

**Comment by crichID** [comment]
@peter-moraza this is because you still  need to accept the invitation  to  collaborate on this repository: https://github.com/githubschool/conflict-practice-peter-moraza/invitations

**Comment by peter-moraza** [comment]
Hi Cynthia,

Checking the “winter-fun” repository I don’t see the Day 5 recording link. Hope you can supply the recording, it was a very informative session.

Regards,

---------
Peter Moraza
Prin IT Engr Applications - Integration
Enterprise Integration Services
Kaiser Permanente
CTO CAS - EIS Development Services
99 S Oakland Ave #041W14
Pasadena, CA 91101
626-564-7356 (office)
8-338-7356 (tie-line)
626-564-3049 (fax)
---------
kp.org/thrive<http://kp.org/thrive>

**Comment by crichID** [comment]
Hi @peter-moraza I just uploaded the video file here: https://vimeo.com/256710477/a00b32cc29 -- it is still processing, but should be done in ~ 1 hour. I will also link it in the winter fun repository.

**Comment by peter-moraza** [comment]
Hi Cynthia,

Thanks for the video. Day 5 was really so informative, we will definitely apply these techniques on our work projects!

Regards,

---------
Peter Moraza
Prin IT Engr Applications - Integration
Enterprise Integration Services
Kaiser Permanente
CTO CAS - EIS Development Services
99 S Oakland Ave #041W14
Pasadena, CA 91101
626-564-7356 (office)
8-338-7356 (tie-line)
626-564-3049 (fax)
---------
kp.org/thrive<http://kp.org/thrive>

**Pull request merged**
